/**
 * Integrity tests for the v4 moderation model bundle on disk.
 *
 * The model is regenerated by `scripts/rebuild_v4_from_tfjs.py` from the HF
 * tfjs export. The script rebuilds the architecture in Keras 3, loads the
 * uint8-quantized weights, and re-emits a TFJS graph-model. These tests
 * catch regressions where someone runs the script with bad args, the source
 * weights drift, or the asset files get corrupted in a merge.
 *
 * Why disk-level assertions (not behavioural): tf.loadGraphModel cannot run
 * inside the Jest/JSDOM environment (it needs the native tensor backend),
 * so we validate the model.json shape declarations + weight manifest
 * instead. Behavioural smoke testing happens on a real device.
 */

import fs from "fs";
import path from "path";

const ROOT = path.resolve(__dirname, "../../../../assets/models/v4-tfjs");
const PUBLIC_ROOT = path.resolve(
  __dirname,
  "../../../../public/models/v4-tfjs",
);

interface ModelJson {
  format?: string;
  signature?: {
    inputs?: Record<string, { tensorShape?: { dim?: { size?: string }[] } }>;
    outputs?: Record<string, { tensorShape?: { dim?: { size?: string }[] } }>;
  };
  weightsManifest?: {
    paths: string[];
    weights: { name: string; shape: number[]; dtype: string }[];
  }[];
}

function readModelJson(dir: string): ModelJson {
  return JSON.parse(fs.readFileSync(path.join(dir, "model.json"), "utf-8"));
}

function dims(shape?: { dim?: { size?: string }[] }): (number | string)[] {
  return (shape?.dim ?? []).map((d) => {
    const s = d.size ?? "";
    const n = Number(s);
    return Number.isFinite(n) ? n : s;
  });
}

describe("v4 model bundle (assets/models/v4-tfjs/)", () => {
  let model: ModelJson;

  beforeAll(() => {
    model = readModelJson(ROOT);
  });

  it("is in graph-model format (so it bypasses tfjs-layers / Keras 3 issues)", () => {
    expect(model.format).toBe("graph-model");
  });

  it("declares a 224x224 RGB image input", () => {
    const inputs = model.signature?.inputs ?? {};
    const inputKeys = Object.keys(inputs);
    expect(inputKeys.length).toBeGreaterThanOrEqual(1);
    const inputShape = dims(inputs[inputKeys[0]].tensorShape);
    // batch dim is symbolic (-1), then 224x224x3
    expect(inputShape).toEqual([-1, 224, 224, 3]);
  });

  it("declares a 3-class output (healthy / not_food / unhealthy)", () => {
    const outputs = model.signature?.outputs ?? {};
    const outputKeys = Object.keys(outputs);
    expect(outputKeys.length).toBe(1);
    const outShape = dims(outputs[outputKeys[0]].tensorShape);
    expect(outShape).toEqual([-1, 3]);
  });

  it("ships a single weight shard referenced by the manifest", () => {
    const manifest = model.weightsManifest?.[0];
    expect(manifest).toBeDefined();
    expect(manifest!.paths).toEqual(["group1-shard1of1.bin"]);
    expect(fs.existsSync(path.join(ROOT, "group1-shard1of1.bin"))).toBe(true);
  });

  it("contains a Dense(_, 3) head as the last classifying weight", () => {
    const weights = model.weightsManifest?.[0].weights ?? [];
    // Find a weight with shape [N, 3] — that's the final Dense kernel
    const denseKernel = weights.find(
      (w) => w.shape.length === 2 && w.shape[1] === 3,
    );
    expect(denseKernel).toBeDefined();
  });

  it("has the Dense head kernel as a float32 [N, 3] tensor", () => {
    // The rebuild script's main job is to dequantize the HF uint8 weights
    // back to float32 and feed them into a 3-class Dense head. This test
    // pins both invariants. Graph constants (int32 paddings, reshape
    // shapes, reduction_indices) are intentionally not checked since they
    // come from the TF SavedModel export, not from the rebuild path.
    const weights = model.weightsManifest?.[0].weights ?? [];
    const denseKernel = weights.find(
      (w) => w.shape.length === 2 && w.shape[1] === 3,
    );
    expect(denseKernel).toBeDefined();
    expect(denseKernel!.dtype).toBe("float32");
    // 576-dim feature vector out of MobileNetV3Small + GAP
    expect(denseKernel!.shape[0]).toBe(576);
  });

  it("has a weight shard size consistent with the declared tensor dtypes", () => {
    const weights = model.weightsManifest?.[0].weights ?? [];
    const bytesPer: Record<string, number> = {
      float32: 4,
      float16: 2,
      int64: 8,
      int32: 4,
      int16: 2,
      uint8: 1,
      bool: 1,
    };
    const expectedBytes = weights.reduce((acc, w) => {
      const elems = w.shape.reduce((p, s) => p * s, 1);
      return acc + elems * (bytesPer[w.dtype] ?? 4);
    }, 0);
    const actualBytes = fs.statSync(
      path.join(ROOT, "group1-shard1of1.bin"),
    ).size;
    // Allow ~1KB slack for any TF-side alignment padding in the conversion.
    expect(Math.abs(actualBytes - expectedBytes)).toBeLessThan(1024);
  });

  it("is mirrored in public/ for the web bundle", () => {
    expect(fs.existsSync(path.join(PUBLIC_ROOT, "model.json"))).toBe(true);
    expect(fs.existsSync(path.join(PUBLIC_ROOT, "group1-shard1of1.bin"))).toBe(
      true,
    );
    const pubModel = readModelJson(PUBLIC_ROOT);
    expect(pubModel.format).toBe("graph-model");
    // Same output shape on the web copy
    const pubOutputs = pubModel.signature?.outputs ?? {};
    const pubOut = dims(Object.values(pubOutputs)[0]?.tensorShape);
    expect(pubOut).toEqual([-1, 3]);
  });
});
